Update required lxml version
Something seems to be wrong with it. Windows CI job is failing with:

py: exit 1 (6.58 seconds) D:\a\glyphsLib\glyphsLib> python -I -m pip install -r requirements.txt -r requirements-dev.txt pid=3368
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
  py: FAIL code 1 (11.77 seconds)

  evaluation failed :( (12.05 seconds)
    lxml==4.9.1 from https://files.pythonhosted.org/packages/5b/2a/b29ca0616397e6d5608255cd0f635a6786892fec898eb65fe8aa4347e9c0/lxml-4.9.1-cp37-cp37m-win_amd64.whl (from -r requirements-dev.txt (line 49)):

        Expected sha256 eea5d6443b093e1545ad0210e6cf27f920482bfcf5c77cdc8596aec73523bb7e

             Got        406f265a44905c7de1e6f3d598d451a56652abf587acab28a4906896da56d434